/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../../common";

export interface BridgeableTokenP_EventsLibInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeableTokenReceived"
      | "BridgeableTokenSent"
      | "DailyCreditLimitSet"
      | "DailyDebitLimitSet"
      | "FeesRateSet"
      | "FeesRecipientSet"
      | "GlobalCreditLimitSet"
      | "GlobalDebitLimitSet"
      | "IsolateModeToggled"
      | "OFTSwapped"
      | "PrincipalTokenCredited"
      | "PrincipalTokenDebited"
  ): EventFragment;
}

export namespace BridgeableTokenReceivedEvent {
  export type InputTuple = [
    guid: BytesLike,
    srcEid: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amountReceived: BigNumberish,
    oftReceived: BigNumberish,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    guid: string,
    srcEid: bigint,
    from: string,
    to: string,
    amountReceived: bigint,
    oftReceived: bigint,
    feeAmount: bigint
  ];
  export interface OutputObject {
    guid: string;
    srcEid: bigint;
    from: string;
    to: string;
    amountReceived: bigint;
    oftReceived: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeableTokenSentEvent {
  export type InputTuple = [
    guid: BytesLike,
    dstEid: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    nativeFeeAmount: BigNumberish,
    isPrincipalTokenSent: boolean,
    amountSent: BigNumberish,
    amountReceive: BigNumberish
  ];
  export type OutputTuple = [
    guid: string,
    dstEid: bigint,
    from: string,
    to: string,
    nativeFeeAmount: bigint,
    isPrincipalTokenSent: boolean,
    amountSent: bigint,
    amountReceive: bigint
  ];
  export interface OutputObject {
    guid: string;
    dstEid: bigint;
    from: string;
    to: string;
    nativeFeeAmount: bigint;
    isPrincipalTokenSent: boolean;
    amountSent: bigint;
    amountReceive: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyCreditLimitSetEvent {
  export type InputTuple = [dailyCreditLimit: BigNumberish];
  export type OutputTuple = [dailyCreditLimit: bigint];
  export interface OutputObject {
    dailyCreditLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyDebitLimitSetEvent {
  export type InputTuple = [dailyDebitLimit: BigNumberish];
  export type OutputTuple = [dailyDebitLimit: bigint];
  export interface OutputObject {
    dailyDebitLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesRateSetEvent {
  export type InputTuple = [feesRate: BigNumberish];
  export type OutputTuple = [feesRate: bigint];
  export interface OutputObject {
    feesRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesRecipientSetEvent {
  export type InputTuple = [feesRecipient: AddressLike];
  export type OutputTuple = [feesRecipient: string];
  export interface OutputObject {
    feesRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalCreditLimitSetEvent {
  export type InputTuple = [globalCreditLimit: BigNumberish];
  export type OutputTuple = [globalCreditLimit: bigint];
  export interface OutputObject {
    globalCreditLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalDebitLimitSetEvent {
  export type InputTuple = [globalDebitLimit: BigNumberish];
  export type OutputTuple = [globalDebitLimit: bigint];
  export interface OutputObject {
    globalDebitLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IsolateModeToggledEvent {
  export type InputTuple = [isolateMode: boolean];
  export type OutputTuple = [isolateMode: boolean];
  export interface OutputObject {
    isolateMode: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OFTSwappedEvent {
  export type InputTuple = [
    caller: AddressLike,
    to: AddressLike,
    amountSwapped: BigNumberish,
    principalTokenAmountCredited: BigNumberish,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    to: string,
    amountSwapped: bigint,
    principalTokenAmountCredited: bigint,
    feeAmount: bigint
  ];
  export interface OutputObject {
    caller: string;
    to: string;
    amountSwapped: bigint;
    principalTokenAmountCredited: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrincipalTokenCreditedEvent {
  export type InputTuple = [to: AddressLike, amountCredited: BigNumberish];
  export type OutputTuple = [to: string, amountCredited: bigint];
  export interface OutputObject {
    to: string;
    amountCredited: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrincipalTokenDebitedEvent {
  export type InputTuple = [from: AddressLike, amountDebited: BigNumberish];
  export type OutputTuple = [from: string, amountDebited: bigint];
  export interface OutputObject {
    from: string;
    amountDebited: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeableTokenP_EventsLib extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeableTokenP_EventsLib;
  waitForDeployment(): Promise<this>;

  interface: BridgeableTokenP_EventsLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BridgeableTokenReceived"
  ): TypedContractEvent<
    BridgeableTokenReceivedEvent.InputTuple,
    BridgeableTokenReceivedEvent.OutputTuple,
    BridgeableTokenReceivedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeableTokenSent"
  ): TypedContractEvent<
    BridgeableTokenSentEvent.InputTuple,
    BridgeableTokenSentEvent.OutputTuple,
    BridgeableTokenSentEvent.OutputObject
  >;
  getEvent(
    key: "DailyCreditLimitSet"
  ): TypedContractEvent<
    DailyCreditLimitSetEvent.InputTuple,
    DailyCreditLimitSetEvent.OutputTuple,
    DailyCreditLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "DailyDebitLimitSet"
  ): TypedContractEvent<
    DailyDebitLimitSetEvent.InputTuple,
    DailyDebitLimitSetEvent.OutputTuple,
    DailyDebitLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "FeesRateSet"
  ): TypedContractEvent<
    FeesRateSetEvent.InputTuple,
    FeesRateSetEvent.OutputTuple,
    FeesRateSetEvent.OutputObject
  >;
  getEvent(
    key: "FeesRecipientSet"
  ): TypedContractEvent<
    FeesRecipientSetEvent.InputTuple,
    FeesRecipientSetEvent.OutputTuple,
    FeesRecipientSetEvent.OutputObject
  >;
  getEvent(
    key: "GlobalCreditLimitSet"
  ): TypedContractEvent<
    GlobalCreditLimitSetEvent.InputTuple,
    GlobalCreditLimitSetEvent.OutputTuple,
    GlobalCreditLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "GlobalDebitLimitSet"
  ): TypedContractEvent<
    GlobalDebitLimitSetEvent.InputTuple,
    GlobalDebitLimitSetEvent.OutputTuple,
    GlobalDebitLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "IsolateModeToggled"
  ): TypedContractEvent<
    IsolateModeToggledEvent.InputTuple,
    IsolateModeToggledEvent.OutputTuple,
    IsolateModeToggledEvent.OutputObject
  >;
  getEvent(
    key: "OFTSwapped"
  ): TypedContractEvent<
    OFTSwappedEvent.InputTuple,
    OFTSwappedEvent.OutputTuple,
    OFTSwappedEvent.OutputObject
  >;
  getEvent(
    key: "PrincipalTokenCredited"
  ): TypedContractEvent<
    PrincipalTokenCreditedEvent.InputTuple,
    PrincipalTokenCreditedEvent.OutputTuple,
    PrincipalTokenCreditedEvent.OutputObject
  >;
  getEvent(
    key: "PrincipalTokenDebited"
  ): TypedContractEvent<
    PrincipalTokenDebitedEvent.InputTuple,
    PrincipalTokenDebitedEvent.OutputTuple,
    PrincipalTokenDebitedEvent.OutputObject
  >;

  filters: {
    "BridgeableTokenReceived(bytes32,uint32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      BridgeableTokenReceivedEvent.InputTuple,
      BridgeableTokenReceivedEvent.OutputTuple,
      BridgeableTokenReceivedEvent.OutputObject
    >;
    BridgeableTokenReceived: TypedContractEvent<
      BridgeableTokenReceivedEvent.InputTuple,
      BridgeableTokenReceivedEvent.OutputTuple,
      BridgeableTokenReceivedEvent.OutputObject
    >;

    "BridgeableTokenSent(bytes32,uint32,address,address,uint256,bool,uint256,uint256)": TypedContractEvent<
      BridgeableTokenSentEvent.InputTuple,
      BridgeableTokenSentEvent.OutputTuple,
      BridgeableTokenSentEvent.OutputObject
    >;
    BridgeableTokenSent: TypedContractEvent<
      BridgeableTokenSentEvent.InputTuple,
      BridgeableTokenSentEvent.OutputTuple,
      BridgeableTokenSentEvent.OutputObject
    >;

    "DailyCreditLimitSet(uint256)": TypedContractEvent<
      DailyCreditLimitSetEvent.InputTuple,
      DailyCreditLimitSetEvent.OutputTuple,
      DailyCreditLimitSetEvent.OutputObject
    >;
    DailyCreditLimitSet: TypedContractEvent<
      DailyCreditLimitSetEvent.InputTuple,
      DailyCreditLimitSetEvent.OutputTuple,
      DailyCreditLimitSetEvent.OutputObject
    >;

    "DailyDebitLimitSet(uint256)": TypedContractEvent<
      DailyDebitLimitSetEvent.InputTuple,
      DailyDebitLimitSetEvent.OutputTuple,
      DailyDebitLimitSetEvent.OutputObject
    >;
    DailyDebitLimitSet: TypedContractEvent<
      DailyDebitLimitSetEvent.InputTuple,
      DailyDebitLimitSetEvent.OutputTuple,
      DailyDebitLimitSetEvent.OutputObject
    >;

    "FeesRateSet(uint16)": TypedContractEvent<
      FeesRateSetEvent.InputTuple,
      FeesRateSetEvent.OutputTuple,
      FeesRateSetEvent.OutputObject
    >;
    FeesRateSet: TypedContractEvent<
      FeesRateSetEvent.InputTuple,
      FeesRateSetEvent.OutputTuple,
      FeesRateSetEvent.OutputObject
    >;

    "FeesRecipientSet(address)": TypedContractEvent<
      FeesRecipientSetEvent.InputTuple,
      FeesRecipientSetEvent.OutputTuple,
      FeesRecipientSetEvent.OutputObject
    >;
    FeesRecipientSet: TypedContractEvent<
      FeesRecipientSetEvent.InputTuple,
      FeesRecipientSetEvent.OutputTuple,
      FeesRecipientSetEvent.OutputObject
    >;

    "GlobalCreditLimitSet(uint256)": TypedContractEvent<
      GlobalCreditLimitSetEvent.InputTuple,
      GlobalCreditLimitSetEvent.OutputTuple,
      GlobalCreditLimitSetEvent.OutputObject
    >;
    GlobalCreditLimitSet: TypedContractEvent<
      GlobalCreditLimitSetEvent.InputTuple,
      GlobalCreditLimitSetEvent.OutputTuple,
      GlobalCreditLimitSetEvent.OutputObject
    >;

    "GlobalDebitLimitSet(uint256)": TypedContractEvent<
      GlobalDebitLimitSetEvent.InputTuple,
      GlobalDebitLimitSetEvent.OutputTuple,
      GlobalDebitLimitSetEvent.OutputObject
    >;
    GlobalDebitLimitSet: TypedContractEvent<
      GlobalDebitLimitSetEvent.InputTuple,
      GlobalDebitLimitSetEvent.OutputTuple,
      GlobalDebitLimitSetEvent.OutputObject
    >;

    "IsolateModeToggled(bool)": TypedContractEvent<
      IsolateModeToggledEvent.InputTuple,
      IsolateModeToggledEvent.OutputTuple,
      IsolateModeToggledEvent.OutputObject
    >;
    IsolateModeToggled: TypedContractEvent<
      IsolateModeToggledEvent.InputTuple,
      IsolateModeToggledEvent.OutputTuple,
      IsolateModeToggledEvent.OutputObject
    >;

    "OFTSwapped(address,address,uint256,uint256,uint256)": TypedContractEvent<
      OFTSwappedEvent.InputTuple,
      OFTSwappedEvent.OutputTuple,
      OFTSwappedEvent.OutputObject
    >;
    OFTSwapped: TypedContractEvent<
      OFTSwappedEvent.InputTuple,
      OFTSwappedEvent.OutputTuple,
      OFTSwappedEvent.OutputObject
    >;

    "PrincipalTokenCredited(address,uint256)": TypedContractEvent<
      PrincipalTokenCreditedEvent.InputTuple,
      PrincipalTokenCreditedEvent.OutputTuple,
      PrincipalTokenCreditedEvent.OutputObject
    >;
    PrincipalTokenCredited: TypedContractEvent<
      PrincipalTokenCreditedEvent.InputTuple,
      PrincipalTokenCreditedEvent.OutputTuple,
      PrincipalTokenCreditedEvent.OutputObject
    >;

    "PrincipalTokenDebited(address,uint256)": TypedContractEvent<
      PrincipalTokenDebitedEvent.InputTuple,
      PrincipalTokenDebitedEvent.OutputTuple,
      PrincipalTokenDebitedEvent.OutputObject
    >;
    PrincipalTokenDebited: TypedContractEvent<
      PrincipalTokenDebitedEvent.InputTuple,
      PrincipalTokenDebitedEvent.OutputTuple,
      PrincipalTokenDebitedEvent.OutputObject
    >;
  };
}
