/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FlashParallelTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CALLBACK_SUCCESS"
      | "UPGRADE_INTERFACE_VERSION"
      | "accrueInterestToFeeRecipient"
      | "authority"
      | "flashFee"
      | "flashLoan"
      | "flashLoanFeeRecipient"
      | "initialize"
      | "isConsumingScheduledOp"
      | "maxFlashLoan"
      | "proxiableUUID"
      | "setAuthority"
      | "setFlashLoanFeeRecipient"
      | "setFlashLoanParameters"
      | "toggleActiveToken"
      | "tokenMap"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActiveTokenToggled"
      | "AuthorityUpdated"
      | "FlashLoan"
      | "FlashLoanFeeRecipientUpdated"
      | "FlashLoanParametersUpdated"
      | "Initialized"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CALLBACK_SUCCESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accrueInterestToFeeRecipient",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "flashFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoanFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isConsumingScheduledOp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxFlashLoan",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlashLoanFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlashLoanParameters",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleActiveToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMap",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CALLBACK_SUCCESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accrueInterestToFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flashFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flashLoanFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConsumingScheduledOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxFlashLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlashLoanFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlashLoanParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleActiveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ActiveTokenToggledEvent {
  export type InputTuple = [token: AddressLike, isActive: boolean];
  export type OutputTuple = [token: string, isActive: boolean];
  export interface OutputObject {
    token: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorityUpdatedEvent {
  export type InputTuple = [authority: AddressLike];
  export type OutputTuple = [authority: string];
  export interface OutputObject {
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    receiver: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, receiver: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanFeeRecipientUpdatedEvent {
  export type InputTuple = [newFlashLoanFeeRecipient: AddressLike];
  export type OutputTuple = [newFlashLoanFeeRecipient: string];
  export interface OutputObject {
    newFlashLoanFeeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanParametersUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    feesRate: BigNumberish,
    maxBorrowable: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    token: string,
    feesRate: bigint,
    maxBorrowable: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    token: string;
    feesRate: bigint;
    maxBorrowable: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlashParallelToken extends BaseContract {
  connect(runner?: ContractRunner | null): FlashParallelToken;
  waitForDeployment(): Promise<this>;

  interface: FlashParallelTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CALLBACK_SUCCESS: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  accrueInterestToFeeRecipient: TypedContractMethod<
    [tokens: AddressLike[]],
    [bigint[]],
    "nonpayable"
  >;

  authority: TypedContractMethod<[], [string], "view">;

  flashFee: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  flashLoan: TypedContractMethod<
    [
      receiver: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  flashLoanFeeRecipient: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_accessManager: AddressLike, _flashLoanFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  isConsumingScheduledOp: TypedContractMethod<[], [string], "view">;

  maxFlashLoan: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  setAuthority: TypedContractMethod<
    [newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  setFlashLoanFeeRecipient: TypedContractMethod<
    [_newFlashLoanFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setFlashLoanParameters: TypedContractMethod<
    [
      _token: AddressLike,
      _feesRate: BigNumberish,
      _maxBorrowable: BigNumberish,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  toggleActiveToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenMap: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        maxBorrowable: bigint;
        feesRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CALLBACK_SUCCESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accrueInterestToFeeRecipient"
  ): TypedContractMethod<[tokens: AddressLike[]], [bigint[]], "nonpayable">;
  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flashFee"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "flashLoan"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoanFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_accessManager: AddressLike, _flashLoanFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isConsumingScheduledOp"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxFlashLoan"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthority"
  ): TypedContractMethod<[newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFlashLoanFeeRecipient"
  ): TypedContractMethod<
    [_newFlashLoanFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFlashLoanParameters"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _feesRate: BigNumberish,
      _maxBorrowable: BigNumberish,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "toggleActiveToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenMap"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        maxBorrowable: bigint;
        feesRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ActiveTokenToggled"
  ): TypedContractEvent<
    ActiveTokenToggledEvent.InputTuple,
    ActiveTokenToggledEvent.OutputTuple,
    ActiveTokenToggledEvent.OutputObject
  >;
  getEvent(
    key: "AuthorityUpdated"
  ): TypedContractEvent<
    AuthorityUpdatedEvent.InputTuple,
    AuthorityUpdatedEvent.OutputTuple,
    AuthorityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoan"
  ): TypedContractEvent<
    FlashLoanEvent.InputTuple,
    FlashLoanEvent.OutputTuple,
    FlashLoanEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoanFeeRecipientUpdated"
  ): TypedContractEvent<
    FlashLoanFeeRecipientUpdatedEvent.InputTuple,
    FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
    FlashLoanFeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoanParametersUpdated"
  ): TypedContractEvent<
    FlashLoanParametersUpdatedEvent.InputTuple,
    FlashLoanParametersUpdatedEvent.OutputTuple,
    FlashLoanParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "ActiveTokenToggled(address,bool)": TypedContractEvent<
      ActiveTokenToggledEvent.InputTuple,
      ActiveTokenToggledEvent.OutputTuple,
      ActiveTokenToggledEvent.OutputObject
    >;
    ActiveTokenToggled: TypedContractEvent<
      ActiveTokenToggledEvent.InputTuple,
      ActiveTokenToggledEvent.OutputTuple,
      ActiveTokenToggledEvent.OutputObject
    >;

    "AuthorityUpdated(address)": TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;
    AuthorityUpdated: TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;

    "FlashLoan(address,uint256,address)": TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;
    FlashLoan: TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;

    "FlashLoanFeeRecipientUpdated(address)": TypedContractEvent<
      FlashLoanFeeRecipientUpdatedEvent.InputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputObject
    >;
    FlashLoanFeeRecipientUpdated: TypedContractEvent<
      FlashLoanFeeRecipientUpdatedEvent.InputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputObject
    >;

    "FlashLoanParametersUpdated(address,uint16,uint256,bool)": TypedContractEvent<
      FlashLoanParametersUpdatedEvent.InputTuple,
      FlashLoanParametersUpdatedEvent.OutputTuple,
      FlashLoanParametersUpdatedEvent.OutputObject
    >;
    FlashLoanParametersUpdated: TypedContractEvent<
      FlashLoanParametersUpdatedEvent.InputTuple,
      FlashLoanParametersUpdatedEvent.OutputTuple,
      FlashLoanParametersUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
