/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorsLibSol from "./ErrorsLib.sol";
export type { errorsLibSol };
import type * as eventsLibSol from "./EventsLib.sol";
export type { eventsLibSol };
export type { FlashParallelToken } from "./FlashParallelToken";
