/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ReentrancyGuardTransientUpgradeable,
  ReentrancyGuardTransientUpgradeableInterface,
} from "../../../../@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardTransientUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class ReentrancyGuardTransientUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardTransientUpgradeableInterface {
    return new Interface(_abi) as ReentrancyGuardTransientUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyGuardTransientUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ReentrancyGuardTransientUpgradeable;
  }
}
