/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  FlashLoan_ErrorsLib,
  FlashLoan_ErrorsLibInterface,
} from "../../../../contracts/flashloan/ErrorsLib.sol/FlashLoan_ErrorsLib";

const _abi = [
  {
    inputs: [],
    name: "InvalidReturnMessage",
    type: "error",
  },
  {
    inputs: [],
    name: "MaxFeesRateExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "TooBigAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "UnsupportedToken",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220ef59298430d4e8a25931ca66cfd30d6befa455cc6056458c357167c51b7ee6b664736f6c634300081c0033";

type FlashLoan_ErrorsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FlashLoan_ErrorsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FlashLoan_ErrorsLib__factory extends ContractFactory {
  constructor(...args: FlashLoan_ErrorsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FlashLoan_ErrorsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): FlashLoan_ErrorsLib__factory {
    return super.connect(runner) as FlashLoan_ErrorsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FlashLoan_ErrorsLibInterface {
    return new Interface(_abi) as FlashLoan_ErrorsLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FlashLoan_ErrorsLib {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FlashLoan_ErrorsLib;
  }
}
