/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBridgeableTokenP__factory } from "./IBridgeableTokenP__factory";
export { ITokenP__factory } from "./ITokenP__factory";
