/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  AddressCast,
  AddressCastInterface,
} from "../../../../../@layerzerolabs/lz-evm-protocol-v2/contracts/libs/AddressCast";

const _abi = [
  {
    inputs: [],
    name: "AddressCast_InvalidAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressCast_InvalidSizeForAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200ea6defb00ef962e9d660a267e29678801c29da8a7f1981785fc7ea3d5ca0dfa64736f6c634300081c0033";

type AddressCastConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressCastConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AddressCast__factory extends ContractFactory {
  constructor(...args: AddressCastConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AddressCast & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AddressCast__factory {
    return super.connect(runner) as AddressCast__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressCastInterface {
    return new Interface(_abi) as AddressCastInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AddressCast {
    return new Contract(address, _abi, runner) as unknown as AddressCast;
  }
}
