/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface FlashLoan_EventsLibInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "ActiveTokenToggled"
      | "FlashLoan"
      | "FlashLoanFeeRecipientUpdated"
      | "FlashLoanParametersUpdated"
  ): EventFragment;
}

export namespace ActiveTokenToggledEvent {
  export type InputTuple = [token: AddressLike, isActive: boolean];
  export type OutputTuple = [token: string, isActive: boolean];
  export interface OutputObject {
    token: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    receiver: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, receiver: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanFeeRecipientUpdatedEvent {
  export type InputTuple = [newFlashLoanFeeRecipient: AddressLike];
  export type OutputTuple = [newFlashLoanFeeRecipient: string];
  export interface OutputObject {
    newFlashLoanFeeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanParametersUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    feesRate: BigNumberish,
    maxBorrowable: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    token: string,
    feesRate: bigint,
    maxBorrowable: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    token: string;
    feesRate: bigint;
    maxBorrowable: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlashLoan_EventsLib extends BaseContract {
  connect(runner?: ContractRunner | null): FlashLoan_EventsLib;
  waitForDeployment(): Promise<this>;

  interface: FlashLoan_EventsLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ActiveTokenToggled"
  ): TypedContractEvent<
    ActiveTokenToggledEvent.InputTuple,
    ActiveTokenToggledEvent.OutputTuple,
    ActiveTokenToggledEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoan"
  ): TypedContractEvent<
    FlashLoanEvent.InputTuple,
    FlashLoanEvent.OutputTuple,
    FlashLoanEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoanFeeRecipientUpdated"
  ): TypedContractEvent<
    FlashLoanFeeRecipientUpdatedEvent.InputTuple,
    FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
    FlashLoanFeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoanParametersUpdated"
  ): TypedContractEvent<
    FlashLoanParametersUpdatedEvent.InputTuple,
    FlashLoanParametersUpdatedEvent.OutputTuple,
    FlashLoanParametersUpdatedEvent.OutputObject
  >;

  filters: {
    "ActiveTokenToggled(address,bool)": TypedContractEvent<
      ActiveTokenToggledEvent.InputTuple,
      ActiveTokenToggledEvent.OutputTuple,
      ActiveTokenToggledEvent.OutputObject
    >;
    ActiveTokenToggled: TypedContractEvent<
      ActiveTokenToggledEvent.InputTuple,
      ActiveTokenToggledEvent.OutputTuple,
      ActiveTokenToggledEvent.OutputObject
    >;

    "FlashLoan(address,uint256,address)": TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;
    FlashLoan: TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;

    "FlashLoanFeeRecipientUpdated(address)": TypedContractEvent<
      FlashLoanFeeRecipientUpdatedEvent.InputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputObject
    >;
    FlashLoanFeeRecipientUpdated: TypedContractEvent<
      FlashLoanFeeRecipientUpdatedEvent.InputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputTuple,
      FlashLoanFeeRecipientUpdatedEvent.OutputObject
    >;

    "FlashLoanParametersUpdated(address,uint16,uint256,bool)": TypedContractEvent<
      FlashLoanParametersUpdatedEvent.InputTuple,
      FlashLoanParametersUpdatedEvent.OutputTuple,
      FlashLoanParametersUpdatedEvent.OutputObject
    >;
    FlashLoanParametersUpdated: TypedContractEvent<
      FlashLoanParametersUpdatedEvent.InputTuple,
      FlashLoanParametersUpdatedEvent.OutputTuple,
      FlashLoanParametersUpdatedEvent.OutputObject
    >;
  };
}
