import { ExecutorOptionType } from "@layerzerolabs/lz-v2-utilities";
import { OAppEnforcedOption } from "@layerzerolabs/toolbox-hardhat";
import { Network } from "./types";

export enum NETWORKS {
  AVALANCHE = "AVALANCHE",
  ARBITRUM = "ARBITRUM",
  BASE = "BASE",
  BERACHAIN = "BERACHAIN",
  BSC = "BSC",
  GNOSIS = "GNOSIS",
  HYPERLIQUID = "HYPERLIQUID",
  INK = "INK",
  MAINNET = "MAINNET",
  OPTIMISM = "OPTIMISM",
  POLYGON = "POLYGON",
  SCROLL = "SCROLL",
  SEI = "SEI",
  SONIC = "SONIC",
  TAC = "TAC",
  UNICHAIN = "UNICHAIN",
}

export const MAINNET_CONFIRMATIONS_BLOCKS = 20;
export const POLYGON_CONFIRMATIONS_BLOCKS = 512;
export const BASE_CONFIRMATIONS_BLOCKS = 10;
export const OPTIMISM_CONFIRMATIONS_BLOCKS = 20;
export const ARBITRUM_CONFIRMATIONS_BLOCKS = 20;
export const SONIC_CONFIRMATIONS_BLOCKS = 20;
export const SEI_CONFIRMATIONS_BLOCKS = 5;
export const AVALANCHE_CONFIRMATIONS_BLOCKS = 12;
export const UNICHAIN_CONFIRMATIONS_BLOCKS = 20;
export const BERACHAIN_CONFIRMATIONS_BLOCKS = 20;
export const GNOSIS_CONFIRMATIONS_BLOCKS = 5;
export const SCROLL_CONFIRMATIONS_BLOCKS = 20;
export const BSC_CONFIRMATIONS_BLOCKS = 20;
export const HYPERLIQUID_CONFIRMATIONS_BLOCKS = 1;
export const INK_CONFIRMATIONS_BLOCKS = 20;
export const TAC_CONFIRMATIONS_BLOCKS = 20;

export const DVNs: [string[], [string[], number] | []] = [
  ["LayerZero Labs", "Nethermind"],
  [["Horizen", "P2P"], 1],
];

export const EVM_ENFORCED_OPTIONS: OAppEnforcedOption[] = [
  {
    msgType: 1,
    optionType: ExecutorOptionType.LZ_RECEIVE,
    gas: 80000,
    value: 0,
  },
];

export const CONFIRMATIONS_BLOCKS: Record<Network, number> = {
  [NETWORKS.AVALANCHE]: AVALANCHE_CONFIRMATIONS_BLOCKS,
  [NETWORKS.ARBITRUM]: ARBITRUM_CONFIRMATIONS_BLOCKS,
  [NETWORKS.BASE]: BASE_CONFIRMATIONS_BLOCKS,
  [NETWORKS.BERACHAIN]: BERACHAIN_CONFIRMATIONS_BLOCKS,
  [NETWORKS.BSC]: BSC_CONFIRMATIONS_BLOCKS,
  [NETWORKS.GNOSIS]: GNOSIS_CONFIRMATIONS_BLOCKS,
  [NETWORKS.HYPERLIQUID]: HYPERLIQUID_CONFIRMATIONS_BLOCKS,
  [NETWORKS.INK]: INK_CONFIRMATIONS_BLOCKS,
  [NETWORKS.MAINNET]: MAINNET_CONFIRMATIONS_BLOCKS,
  [NETWORKS.OPTIMISM]: OPTIMISM_CONFIRMATIONS_BLOCKS,
  [NETWORKS.POLYGON]: POLYGON_CONFIRMATIONS_BLOCKS,
  [NETWORKS.SCROLL]: SCROLL_CONFIRMATIONS_BLOCKS,
  [NETWORKS.SEI]: SEI_CONFIRMATIONS_BLOCKS,
  [NETWORKS.SONIC]: SONIC_CONFIRMATIONS_BLOCKS,
  [NETWORKS.TAC]: TAC_CONFIRMATIONS_BLOCKS,
  [NETWORKS.UNICHAIN]: UNICHAIN_CONFIRMATIONS_BLOCKS,
};
