/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  BridgeableTokenP_EventsLib,
  BridgeableTokenP_EventsLibInterface,
} from "../../../../../contracts/tokens/BridgeableTokenP/EventsLib.sol/BridgeableTokenP_EventsLib";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "guid",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "srcEid",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountReceived",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oftReceived",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
    ],
    name: "BridgeableTokenReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "guid",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "dstEid",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nativeFeeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isPrincipalTokenSent",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountSent",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountReceive",
        type: "uint256",
      },
    ],
    name: "BridgeableTokenSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "dailyCreditLimit",
        type: "uint256",
      },
    ],
    name: "DailyCreditLimitSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "dailyDebitLimit",
        type: "uint256",
      },
    ],
    name: "DailyDebitLimitSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint16",
        name: "feesRate",
        type: "uint16",
      },
    ],
    name: "FeesRateSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "feesRecipient",
        type: "address",
      },
    ],
    name: "FeesRecipientSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "globalCreditLimit",
        type: "uint256",
      },
    ],
    name: "GlobalCreditLimitSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "globalDebitLimit",
        type: "uint256",
      },
    ],
    name: "GlobalDebitLimitSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "isolateMode",
        type: "bool",
      },
    ],
    name: "IsolateModeToggled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountSwapped",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "principalTokenAmountCredited",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
    ],
    name: "OFTSwapped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountCredited",
        type: "uint256",
      },
    ],
    name: "PrincipalTokenCredited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountDebited",
        type: "uint256",
      },
    ],
    name: "PrincipalTokenDebited",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122007074f3794ea2c9b6a5e74c2e47c8d6a0a483d4b88b6fe511b0aac7e77e41f5264736f6c634300081c0033";

type BridgeableTokenP_EventsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeableTokenP_EventsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeableTokenP_EventsLib__factory extends ContractFactory {
  constructor(...args: BridgeableTokenP_EventsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BridgeableTokenP_EventsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BridgeableTokenP_EventsLib__factory {
    return super.connect(runner) as BridgeableTokenP_EventsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeableTokenP_EventsLibInterface {
    return new Interface(_abi) as BridgeableTokenP_EventsLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BridgeableTokenP_EventsLib {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BridgeableTokenP_EventsLib;
  }
}
