/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  TokenP_ErrorsLib,
  TokenP_ErrorsLibInterface,
} from "../../../../../contracts/tokens/TokenP/ErrorsLib.sol/TokenP_ErrorsLib";

const _abi = [
  {
    inputs: [],
    name: "BurnAmountExceedsAllowance",
    type: "error",
  },
  {
    inputs: [],
    name: "NotMinter",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212205b7d99227f32d9007b2776bc0105532a617d5155adc715779b00829970f566ef64736f6c634300081c0033";

type TokenP_ErrorsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TokenP_ErrorsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TokenP_ErrorsLib__factory extends ContractFactory {
  constructor(...args: TokenP_ErrorsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TokenP_ErrorsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TokenP_ErrorsLib__factory {
    return super.connect(runner) as TokenP_ErrorsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TokenP_ErrorsLibInterface {
    return new Interface(_abi) as TokenP_ErrorsLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TokenP_ErrorsLib {
    return new Contract(address, _abi, runner) as unknown as TokenP_ErrorsLib;
  }
}
