/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  BridgeableTokenP_ErrorsLib,
  BridgeableTokenP_ErrorsLibInterface,
} from "../../../../../contracts/tokens/BridgeableTokenP/ErrorsLib.sol/BridgeableTokenP_ErrorsLib";

const _abi = [
  {
    inputs: [],
    name: "DailyDebitLimitReached",
    type: "error",
  },
  {
    inputs: [],
    name: "GlobalDebitLimitReached",
    type: "error",
  },
  {
    inputs: [],
    name: "GlobalLimitOverFlow",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMsgLength",
    type: "error",
  },
  {
    inputs: [],
    name: "IsolateModeLimitReach",
    type: "error",
  },
  {
    inputs: [],
    name: "MaxFeesRateExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "NothingToSwap",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208b02276abd199956a3cec0484cb2ecca111f8cf742e0744a50908e47b08baf9964736f6c634300081c0033";

type BridgeableTokenP_ErrorsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeableTokenP_ErrorsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeableTokenP_ErrorsLib__factory extends ContractFactory {
  constructor(...args: BridgeableTokenP_ErrorsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BridgeableTokenP_ErrorsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BridgeableTokenP_ErrorsLib__factory {
    return super.connect(runner) as BridgeableTokenP_ErrorsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeableTokenP_ErrorsLibInterface {
    return new Interface(_abi) as BridgeableTokenP_ErrorsLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BridgeableTokenP_ErrorsLib {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BridgeableTokenP_ErrorsLib;
  }
}
